package ru.itis.pokerproject.shared.protocol.gameserver;

public enum GameMessageType {
    CONNECT_TO_ROOM_REQUEST,
    CONNECT_TO_ROOM_RESPONSE,
    GET_ROOMS_COUNT_REQUEST,
    GET_ROOMS_COUNT_RESPONSE,
    GET_ROOMS_REQUEST,
    GET_ROOMS_RESPONSE,
    CREATE_ROOM_REQUEST,
    CREATE_ROOM_RESPONSE,
    FIND_ROOM_REQUEST,
    FIND_ROOM_RESPONSE,
    PLAYER_CONNECTED,
    PLAYER_DISCONNECTED,
    PLAYER_IS_READY,
    READY,
    START_GAME,
    RAISE,
    FOLD,
    CALL,
    CHECK,
    ERROR
}
